version: '3.1'
services:
  web:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db
    tty: true
    links: 
      - db
    stdin_open: true
  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_USER: microweber
      POSTGRES_PASSWORD: microweber
      POSTGRES_DB: microweber